trigger:
- main  # or your branch name

pool:
  name: self-hosted  # your self-hosted agent pool name

variables:
- group: aws-credentials  # variable group from ADO Library

stages:
- stage: DeployCF
  jobs:
  - job: Deploy
    steps:
    # 1️⃣ Checkout your repo
    - checkout: self

    # 2️⃣ Configure AWS CLI with creds from Library
    - powershell: |
        aws configure set aws_access_key_id "$(AWS_ACCESS_KEY_ID)"
        aws configure set aws_secret_access_key "$(AWS_SECRET_ACCESS_KEY)"
        aws configure set default.region "$(AWS_DEFAULT_REGION)"
      displayName: "Configure AWS CLI"

    # 3️⃣ Deploy the CloudFormation stack
    - powershell: |
        Write-Host "Deploying S3 bucket stack to AWS..."
        aws cloudformation deploy `
          --template-file "$(Build.SourcesDirectory)/s3-bucket.yml" `
          --stack-name my-s3-stack `
          --capabilities CAPABILITY_NAMED_IAM
      displayName: "Deploy CloudFormation Stack"
